import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { FooterSection } from "./components/footer";
import { HeaderSection } from "./components/header";

const inter = Inter({ subsets: ["latin"] });
import ThemeProvider from "./theme-provider";
export const metadata: Metadata = {
	title: "Steam Theme Portfolio",
	description: "Steam theme portfolio generated by create next app",
	icons: "/steam.png"
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html
			className="p-2"
			lang="en"
		>
			<body
				className={inter.className}
			>
				<ThemeProvider>
					<HeaderSection />
					{children}
					<FooterSection />
				</ThemeProvider>
			</body>
		</html>
	);
}
