import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { FooterSection } from "./components/footer";
import { HeaderSection } from "./components/header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html
			className="p-2"
			lang="en"
		>
			<body
				className={`${inter.className}`}
			>
				<HeaderSection />
				{children}
				<FooterSection />
			</body>
		</html>
	);
}
